# sources.yaml
sources:

  # ======================
  # Global / UK
  # ======================
  - name: BBC
    url: https://www.bbc.com
    allow_url_regex: '(?i)(bbc\.com|bbc\.co\.uk)/(news|business|sport)/articles/'
    deny_url_regex: '(?i)/(live|av|video|audio|signin|register|privacy|cookies)'

  - name: The Guardian
    url: https://www.theguardian.com/international
    allow_url_regex: '(?i)theguardian\.com/.+/\d{4}/[a-z]{3}/\d{1,2}/'
    deny_url_regex: '(?i)/(live|video|audio|help|info|privacy|cookies)'

  - name: Financial Times
    url: https://www.ft.com
    allow_url_regex: '(?i)ft\.com/content/'
    deny_url_regex: '(?i)/(video|podcast|live|privacy|cookies)'

  - name: Reuters
    url: https://www.reuters.com/world/
    deny_url_regex: '(?i)/(video|graphics|live|privacy|cookies)'

  - name: Associated Press
    url: https://apnews.com
    allow_url_regex: '(?i)apnews\.com/article/'
    deny_url_regex: '(?i)/(video|hub|live|privacy|cookies)'

  - name: Nikkei Asia
    url: https://asia.nikkei.com
    allow_url_regex: '(?i)asia\.nikkei\.com/.+'
    deny_url_regex: '(?i)/(video|podcast|live|privacy|cookies)'

  # ======================
  # Netherlands (NL)
  # ======================
  - name: NOS
    url: https://nos.nl
    allow_url_regex: '(?i)nos\.nl/artikel/'
    deny_url_regex: '(?i)/(video|live)'

  - name: NRC
    url: https://www.nrc.nl
    allow_url_regex: '(?i)nrc\.nl/nieuws/\d{4}/\d{2}/\d{2}/'
    deny_url_regex: '(?i)/(video|podcast|privacy|cookies)'

  - name: Volkskrant
    url: https://www.volkskrant.nl
    allow_url_regex: '(?i)volkskrant\.nl/.+~[a-z0-9]+/$'
    deny_url_regex: '(?i)/(video|podcast|privacy|cookies)'

  # ======================
  # Germany (DE)
  # ======================
  - name: Tagesschau
    url: https://www.tagesschau.de
    allow_url_regex: '(?i)tagesschau\.de/.+\.html$'
    deny_url_regex: '(?i)/(multimedia|video|audio|livestream|sendung|wetter|kontakt|impressum|datenschutz|tagesthemen/)'

  - name: DW
    url: https://www.dw.com/en/top-stories/s-9097
    allow_url_regex: '(?i)dw\.com/.+-\d+$'
    deny_url_regex: '(?i)/(av-|media|podcast|datenschutz|imprint)'

  - name: Spiegel
    url: https://www.spiegel.de
    allow_url_regex: '(?i)^https?://(www\.)?spiegel\.de/.+-a-[0-9a-f-]+(?:\.html)?/?$'
    deny_url_regex: '(?i)(gruppenkonto\.spiegel\.de|/spiele/|/abo|/kuendigung|/service/|datenschutz|impressum|privacy|cookies|video|podcast|audio)'

  - name: Süddeutsche Zeitung
    url: https://www.sueddeutsche.de
    allow_url_regex: '(?i)^https?://(www\.)?sueddeutsche\.de/.+(?:~[a-z0-9]+|[a-z]{2}\.\d+)(?:\?.*)?$'
    deny_url_regex: '(?i)(/thema/|/gutscheine|/raetsel|datenschutz|impressum|privacy|cookies|video|podcast)'

  - name: FAZ
    url: https://www.faz.net/aktuell/
    allow_url_regex: '(?i)faz\.net/.+-\d{7,}\.html$'
    deny_url_regex: '(?i)/(video|podcast|datenschutz|impressum|newsletter|liveticker|liveblog)'

  - name: Die Welt
    url: https://www.welt.de
    deny_url_regex: '(?i)/(video|podcast|live|impressum|datenschutz)'

  # ======================
  # Middle East / Africa
  # ======================
  - name: Middle East Eye
    url: https://www.middleeasteye.net
    allow_url_regex: '(?i)^https?://(www\.)?middleeasteye\.net/(?!topics/|authors/|tags/|newsletter|about|contact|privacy|cookies|support|donate|video|podcast|search|user/)[a-z0-9-]+(?:/[a-z0-9-]+){1,3}/?$'
    deny_url_regex: '(?i)(/topics/|/authors/|/tags/|/newsletter|/about|/contact|/privacy|/cookies|/support|/donate|/video|/podcast|/search|/user/)'

  - name: The Africa Report
    url: https://www.theafricareport.com
    allow_url_regex: '(?i)^https?://(www\.)?theafricareport\.com/\d+/(?!category/|tag/|author/)[a-z0-9-]{8,}/?$'
    deny_url_regex: '(?i)(/category/|/tag/|/author/|/magazine/|/rankings/|/events/|/about|/contact|/privacy|/cookies|/subscribe|/login|/video|/podcast)'

  # ======================
  # United States (US)
  # ======================
  - name: New York Times
    url: https://www.nytimes.com
    allow_url_regex: '(?i)nytimes\.com/\d{4}/\d{2}/\d{2}/'
    deny_url_regex: '(?i)/(interactive|video|live|wirecutter|crosswords|privacy|cookies)'

  - name: Washington Post
    url: https://www.washingtonpost.com
    deny_url_regex: '(?i)/(video|podcasts|games|privacy|cookies)'

  - name: Wall Street Journal
    url: https://www.wsj.com
    deny_url_regex: '(?i)/(video|podcasts|live|privacy|cookies)'

  - name: Politico Europe
    url: https://www.politico.eu
    allow_url_regex: '(?i)politico\.eu/article/'
    deny_url_regex: '(?i)/(video|live|privacy|cookies)'

  - name: Euronews (English)
    url: https://www.euronews.com
    allow_url_regex: '(?i)^https?://(www\.)?euronews\.com/(?!video/|live|programs|shows|tag/|apps|about|privacy|cookies)(?:\d{4}/\d{2}/\d{2}/)?[a-z0-9-]+/[a-z0-9-]{12,}/?$'
    deny_url_regex: '(?i)(/video/|/live|/programs/|/shows/|/tag/|/about|/privacy|/cookies|/apps|/podcast)'
