# sources.yaml
sources:
  - name: BBC
    url: https://www.bbc.com
    allow_url_regex: '(?i)bbc\.com/(news|sport|business|future|science|technology)'
    deny_url_regex: '(?i)/(live|av|video|audio|signin|register|privacy|cookies)'
  - name: NOS
    url: https://nos.nl
    allow_url_regex: '(?i)nos\.nl/artikel/'
    deny_url_regex: '(?i)/(video|live)'
  - name: The Guardian
    url: https://www.theguardian.com/international
    allow_url_regex: '(?i)theguardian\.com/'
    deny_url_regex: '(?i)/(live|video|audio|help|info|privacy|cookies)'
